set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" -c "CREATE USER ${DATABASE_USER} WITH PASSWORD '${DATABASE_PASSWORD}' SUPERUSER INHERIT CREATEDB NOCREATEROLE NOREPLICATION;"
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" -c "CREATE DATABASE ${DATABASE_NAME} owner ${DATABASE_USER};"
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" -c "CREATE TABLE outbox (id SERIAL PRIMARY KEY, event_type VARCHAR(255) NOT NULL, event_date_time TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP, environment VARCHAR(255) NOT NULL, event_context JSONB NOT NULL, metadata_version BIGINT DEFAULT 1, processed BOOLEAN DEFAULT FALSE);"
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" -c "CREATE INDEX idx_outbox_processed ON outbox (processed);"